### ISSUE TITLE
File encoding problem on windows

### ISSUE THREAD

**Issue by teddy-otieno** [drozdowsky/django-tracking-model#1]
`    
ERROR: Command errored out with exit status 1:
     command: 'C:\Users\teddy\Desktop\work\pharmily\pharmilybackend\venv\Scripts\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\teddy\\AppData\\Local\\Temp\\pip-req-build-n331psns\\setup.py'"'"'; __file__='"'"'C:\\Users\\teddy\\AppData\\Local\\Temp\\pip-req-build-n331psns\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\teddy\AppData\Local\Temp\pip-pip-egg-info-5te8_pyi'
         cwd: C:\Users\teddy\AppData\Local\Temp\pip-req-build-n331psns\
    Complete output (7 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\teddy\AppData\Local\Temp\pip-req-build-n331psns\setup.py", line 5, in <module>
        README = open(os.path.join(here, 'README.md')).read()
      File "c:\users\teddy\appdata\local\programs\python\python38-32\lib\encodings\cp1252.py", line 23, in decode
        return codecs.charmap_decode(input,self.errors,decoding_table)[0]
    UnicodeDecodeError: 'charmap' codec can't decode byte 0x8f in position 26: character maps to <undefined>
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.`

Fix

`
README = open(os.path.join(here, 'README.md'), encoding="utf8").read()
`

**Comment by drozdowsky** [comment]
Fixed.
